# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CorrectsPapers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 pod 'SwiftyJSON'
pod 'Kingfisher'
pod 'Alamofire'
pod 'SwiftyUserDefaults'
pod 'IQKeyboardManagerSwift'
pod 'IQKeyboardManager'
pod 'SDAutoLayout'
pod 'SnapKit'
pod 'Masonry'
pod 'ZFDownload'
pod 'SDWebImage'
#pod 'ZFPlayer'
pod 'Toast'        #吐司
pod 'MJRefresh'

#微信支付
#pod 'WechatOpenSDK'
pod 'MBProgressHUD'
pod 'AFNetworking'


pod 'RxSwift'
pod 'RxCocoa'

# 分享功能

## 主模块(必须)
#pod 'mob_sharesdk'
#
## UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
#pod 'mob_sharesdk/ShareSDKUI'
#
## 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
#pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
##pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
#
##//（微信sdk不带支付的命令）
#pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'
#
## pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFu'
## Pods for CorrectsPapers
## 使用配置文件分享模块（非必需）
#pod 'mob_sharesdk/ShareSDKConfigurationFile'
#
## 扩展模块（在调用可以弹出我们UI分享方法的时候是必需的）
#pod 'mob_sharesdk/ShareSDKExtension'

end
